### ISSUE TITLE
[bug] Potential bug in M104 or M140 (or G28) => collision of heads at end of print

### ISSUE THREAD

**Issue by SigmaFred** [BCN3D/BCN3DSigma-Firmware#103]
I printed the Calibration Target (dual color) with the Sigma. Gcode was generated with Simply3D.
At the very end of the print (left head) the head was sent towards the parking position of the right head = collision.

I checked the code at the end of the file:
`...`
`T0`
`...`
`M104 S0 T0 ; left extruder off`
`M104 S0 T1 ; right extruder off`
`M140 S0 ; heated bed off`
`G28 X0 Y0 ; move XY to min endstops`
`M84 ; steppers off`

for me that looked fine. But due to the 'collison' problem and as the G28 code worked fine in the rest of the code - I just changed the line sequence a bit:  
`...`
`T0`
`...`
`G28 X0 Y0 ; move XY to min endstops`
`M104 S0 T0 ; left extruder off`
`M104 S0 T1 ; right extruder off`
`M140 S0 ; heated bed off`
`M84 ; steppers off`

And (luckily but also surprisingly for me) this slightly changed sequence worked fine.
Based on that 'behaviour' I would assume that calling M104 or M140 might have an unwanted collateral effect on global variables used by G28.

Though I am not familiar with the programming in such detail - I would assume that 'in theory' the sequence of the Codes used here should not make a difference. For me it seems likely that at least one of the commands (M104, M140 or even G28) might be not properly implemented. 

Has anybody experienced this?
Any comments? 

Thank you.

Sigma Firmware used = 1.2.0

**Comment by chimpusmaximus** [comment]
Same issue here and heard others having same

**Comment by AlejandroGarcia92** [comment]
I have opened a new firmware release candidate in order to fix this kind of issues before an official release. You can find the RC version here https://github.com/BCN3D/BCN3DSigma-Firmware/tree/v01-1.2.2RC , so send us feedback.
