### ISSUE TITLE
FW Bug: FW get stuck when starting "bed leveling" after unload/load filament

### ISSUE THREAD

**Issue by mrcg** [BCN3D/BCN3DSigma-Firmware#105]
FW is hanging if bed leveling feature is started after loading filament.
The issue was observerved with v1.2.0, but is existing since longer time.
Issue is 100% reproducable like this:
1. Unload filament
2. load filament
3. start "bed leveling"
The printbed is moving up and then FW is getting stuck.
The issue can only be resolved by power off/on.

It's quite usual to start bed leveling after filament change and therfore it's quite annoying.

**Comment by Zorgonaute84** [comment]
It's a bug for sure, but honestly, I don't think that perform a bed leveling after a filament change is really necessary. I do not and I never had any troubles.

**Comment by mrcg** [comment]
It's a minor bug existing since long time.
Anyhow it should be fixed and that's the reason why i am reporting this here.

I am personally performing bed leveling always after filament change.
Frist of all i think it's useful because of potential mechanical influence while changing the filament.
Secondly because it's the easiest way to move up the bed after filament change.

**Comment by guillemavila** [comment]
This bug is fixed in the next RC we're publishing next week. We couldn't make it for today because it depends on some Graphical features too.

As @Zorgonaute84 says, it's not really necessary. Anyways by now you can move Z using the feature 'Move Z', that's faster than executing a bed calibration.

Thanks for the feedback!

**Comment by mrcg** [comment]
Is the correction already in the latest 1.2.2RC?
It's not listed in the correction list and the 1.2.2RC which i have loaded (might not be the latest one) still has the issue.

**Comment by AlejandroGarcia92** [comment]
This bug should be fixed on the current fw version.
