### ISSUE TITLE
There is a problem that the screen stops.

### ISSUE THREAD

**Issue by ggangjuk** [BCN3D/BCN3DSigma-Firmware#107]
I bought a new extruder.
I have run the gcode below to get the speed.

M92 E492.45
M500

After that, when the filament load, unload and print are finished, the screen stops.
How can I fix it?

**Comment by guillemavila** [comment]
You should also change the maximum feedrates for the extruders.

Defaults are:
`M92 E152`
`M203 E60`

According to your new steps/unit:
`M92 E492.45`
`M203 E195`
