### ISSUE TITLE
Print artefacts when modifing the settings

### ISSUE THREAD

**Issue by vieillemaison** [BCN3D/BCN3DSigma-Firmware#109]
When I change the temperature setting during the printing with the menu on the LCD. I have some "underextrusion" the time I stay in the setting menu. When I leave the setting menu all goes back in order.

Is it possible that during the time I stayed in the setting menu some temperature regulation is no more done?

My actual firmware version is 1.2.0

**Comment by guillemavila** [comment]
Hello,

this is strange as the PID Controller for temperatures is aways running. What may happen is, if you are working at very low temperatures, when you go to settings and set them even lower the Controller has a bit of inertia and temperatures can go lower than the selected Value. Then underextrusion may occur.

To check if the controller stops working just remove the central cover and look at the blue LEDs at the motherboard. (one for the right hotend, one for the left and one for the bed) When light is on means the heating resistance is consuming, no light means it's cooling down and intermittent light means the controller is maintaining the target temperature. 

* Notice there are also two blue LEDs that should be always on, showing 5V and 24V tensions are ok.

Anyways I highly recommend to update to the latest firmware version (1.2.1).

Have a great Tuesday!
