### ISSUE TITLE
Error 81 - left thermistor not detected

### ISSUE THREAD

**Issue by droomurray** [BCN3D/BCN3DSigma-Firmware#110]
Printer is in garage and temp is around 3 degrees - looking at FW it errors if starting temp is below 5 :-(

Be good if FW had some of the config settings configurable on the menu

**Comment by AlejandroGarcia92** [comment]
We selected below 5 because when the thermistor doesn't detect anything measures 0 degrees.

**Comment by droomurray** [comment]
Ahh ok could there be a method by which it starts to heat for say 30 seconds then checks, by which point it should have got unto temp ?

**Comment by kitusmark** [comment]
Hi @droomurray 
The printer is meant to be operational with a minimum temperature of 15ºC. As you may know by now, you'll experience bad printing results with the temperature so low. 
Thanks
