### ISSUE TITLE
[Enhancement] Firmware uses Z-Lift while changing Nozzles

### ISSUE THREAD

**Issue by BarbecueSilver** [BCN3D/BCN3DSigma-Firmware#113]
The problem is that GCode Z-Lift does not work correctly.

E.g.:
T0 is printing.
Z-lift is executed.
T0 parks at the home position.
Z-lift is reversed
T1 is traveling to print position.
T1 is printing.

Problem: Only half of the Z-lifts are useful.

Solution.:
If a tool change should happen, lift before parking. Park old tool. Get new tool into position. Reverse lifting. Go on with the Gcode. Additional a parameter would be nice to define IF a firmware z-lift shall happen and the height.

Thanks.

**Comment by guillemavila** [comment]
Hello, it can be done using the proper gcode on toolchanges. In fact all profiles from the [Sigma ProGen](https://www.bcn3dtechnologies.com/en/sigma-progen/) come with that feature.

Toimplement it, add these lines to the end of your toolchange gcode:
```
	G91                   ;Change to relative distances
	G1 F{travel_speed} Z2 ;Set movements to travel speed and lift Z 2mm
	G90                   ;Change back to absolute distances```

After that the machine will move to desired X Y, and then move Z back to its normal position (applying the Zlift correctly)
