### ISSUE TITLE
How to Convert to Fat16 

### ISSUE THREAD

**Issue by haqbany** [BCN3D/BCN3DSigma-Firmware#116]
1. Insert the dcard into a reader on your computer 
2. You'll need to know the driveletter it gets assigned. We'll use E: for this guide
3. Click on START 
4. Click on RUN 
5. Type: 

cmd.exe 

6. Click OK or press Enter 
7. In the black window type **FORMAT E: /FS:FAT16** (it could be **/fs:fat** depends on which version windows you have)

That should do it. If you want to go back to FAT32 use "FAT32" as the option. NTFS use NTFS

I hope the card is 2gb or less.

**Comment by kitusmark** [comment]
Hi @haqbany 
The procedure you describe is similar or the same as right click -> format. 
The guide in the wiki is a little bit more accurate as you repartition the card and create a file system from scratch. 

Thanks for the tip!
