### ISSUE TITLE
Noisy sound during purge of the 2nd extruder

### ISSUE THREAD

**Issue by Zorgonaute84** [BCN3D/BCN3DSigma-Firmware#117]
I just upgraded my first generation Sigma with the stepper driver kit. Since this upgrade, I noticed a very noisy sound when I tried to extrude (during purge process) the right extruder and nothing is extruded. The strange thing is, when I want to retract it's working properly, and if I try to extrude from Octoprint, it's working too.

Thanks for your help.

**Comment by Zorgonaute84** [comment]
Ok so I think it was an electronic issue, because the stepper driver is know Out of Service..

**Comment by AlejandroGarcia92** [comment]
It's an electronic issue for sure, contact support.
