### ISSUE TITLE
Bed leveling freezes when PC is connected

### ISSUE THREAD

**Issue by Kevin-Stager** [BCN3D/BCN3DSigma-Firmware#121]
If the printer is connected to simplify3D and I run the bed leveling program from the sigma touch screen it does the first touchdown then the LCD freezes and never continues. 

If the PC is not connected bed leveling seems to work fine.

**Comment by AlejandroGarcia92** [comment]
The simplify3d verbose communication collapses the marlin buffer and it doesn't let to execute the bedleveling program. So I suggest to disable the verbose.

**Comment by Kevin-Stager** [comment]
Ok I tried that and the problem still occured. I will try changing some of the other simplify3D communication settings.  Right now I have no flow control and command buffering is turned on. 
 
The work around of just unplugging before auto leveling is easy enough for now.

**Comment by kitusmark** [comment]
@Kevin-Stager Maybe this helps.
https://github.com/BCN3D/BCN3D-Cura-Windows/wiki/Connect-the-BCN3D-Sigma-to-Simplify-3D

**Comment by AlejandroGarcia92** [comment]
Dear @Kevin-Stager, in the new release should be fixed.
