### ISSUE TITLE
Bed only going down

### ISSUE THREAD

**Issue by enric1976** [BCN3D/BCN3DSigma-Firmware#122]
HI  here's my issue ...when I trying to printing , leveling the bed or try to do anything my bed start going down, never going up..  Yesterday everything was working fine, and today is a total mess.. 

This machine is going from worst to worst..... I had the sd board issue where the sd board is unable to read the sd card... I found a switcher in the sd board and turn it in the other way, then the sd can be read it.  .. this problem happened just 2 days of having the machine new... today 3 month later,  the machine start to going down being imposible to work with my machine,  supposed new,... any help here??? cause  I don't know what to do now...

**Comment by AlejandroGarcia92** [comment]
It seems a electronic issue, please contact support.
