### ISSUE TITLE
Freezing when removing material in right head Firmware 1.2.3

### ISSUE THREAD

**Issue by RhepTheSpring** [BCN3D/BCN3DSigma-Firmware#125]
when removing material or some times loading, in the right head the screen says Processing and just sits there

**Comment by droomurray** [comment]
Yes mine will randomly do this during load / unloads on 1.2.2

**Comment by RhepTheSpring** [comment]
I updated to 1.2.3

and it does it along with other annoying problems like the test calibration pattern failing

**Comment by AlejandroGarcia92** [comment]
I can confirm that it happens randomly. We are going to fix it.
