### ISSUE TITLE
Utilities - Filament - Purge - Does not turn off hotends

### ISSUE THREAD

**Issue by WanaGo** [BCN3D/BCN3DSigma-Firmware#138]
Hello,

I have noticed when doing a purge, you select the left or right extruder and it heats it up, however it does not turn the heaters off. Exiting the purge menu, and the extruders continue to heat up to the set point in the purge menu.
Should this not disable the heater when the menu is changed?
Should it be possible to disable the heater by clicking on the selected extruder again, to unselect it?

v01-1.2.4 Firmware, latest v01-1.2.2 Display code.

**Comment by AlejandroGarcia92** [comment]
We are aware of that but now is not possible to do it on purge menu by screen programming limitations. The only way is going to Temp on main menu otherwise the hotends will cool down while you are on menus after 10 min of inactivity.
