### ISSUE TITLE
Change active Extruder w/ G36

### ISSUE THREAD

**Issue by thesec** [BCN3D/BCN3DSigma-Firmware#151]
It happens to not have filament in the left extruder when I'd like to calibrate.
An option to change the active extruder used for calibration with G36 would be nice to have.

**Comment by AlejandroGarcia92** [comment]
I could implement something like G36 T0/T1 to select the extruder.

**Comment by thesec** [comment]
You must have read my thoughts! ;)
That'd be awesome.

**Comment by AlejandroGarcia92** [comment]
In the next release, this feature will be implemented.

**Comment by thesec** [comment]
Thanks Alejandro!
