### ISSUE TITLE
LCD Screen image upside down after the LCD firmware update SD files v122

### ISSUE THREAD

**Issue by calvinkim207** [BCN3D/BCN3DSigma-Firmware#152]
Hello,
I've just received a new BCN3D Sigma R17 and did a whole firmware update including the SD files v122 (latest; part of v01-1.2.5 package).
The Electronics firmware update was successful, then just followed to the SD Files update as instructed in youtube video.
It was a simple exercise to delete the old files in the SD Card and copy the downloaded files.
When I loaded the SD card back, the firmware reads and works fine except the image is upside down.

Yes I admit, I realised later that I wasn't supposed to update the SD Files for the LCD, but I did and I didn't keep the old ones....
How can I fix this??

**Comment by AlejandroGarcia92** [comment]
You have installed SD files of R16. We have not uploaded the R17's SD files on Github because we don't have in mind to change them by now.

I let you here the R17's SD files

[SD files v122-LCD-R17.zip](https://github.com/BCN3D/BCN3DSigma-Firmware/files/1313887/SD.files.v122-LCD-R17.zip)

**Comment by calvinkim207** [comment]
Thank you very much.
It is now solved!

**Comment by AlejandroGarcia92** [comment]
@svenedt Do you need help?
