### ISSUE TITLE
Fan is on even if M107 is defined in tool change gcode

### ISSUE THREAD

**Issue by lampi87** [BCN3D/BCN3DSigma-Firmware#158]
Hello everyone,

I faced a problem with fan settings and need your advice:
I've created a gcode with Simplify3D. In my Tool Change Script I have defined:
{IF NEWTOOL=0} M106 S55		;enable fan for part material
{IF NEWTOOL=1} M107		;disable fan for support material
In cooling settings in Simplify3D fan was set to 55%

But during printing fan is on for both materials. For extruder 0 and 1.
Any advice from your side?

Thx,
Alexander

**Comment by lampi87** [comment]
After analysing gcode file, seems to be Simplify3D issue

**Comment by AlejandroGarcia92** [comment]
Ok
