### ISSUE TITLE
Language Change

### ISSUE THREAD

**Issue by 4truemodels** [BCN3D/BCN3DSigma-Firmware#159]
Hi there!

I'm trying to change the language showed in the Screen of the Sigma R16.
I know it should be easy, just changing the images for other ones, changing the text or whatever needed but leaving the distribution of the elements just as it is in the original version (so the effect of touching certain areas would remain the same).
The issue is that I have no idea to what to do next to modifying the images... how can I compile the new version?

If you let me the needed instructions (and software I guess) to do so I would introduce both Catalan and Spanish versions of the Firmware. I'm using right now only the 1.2.3 version for my R16 Sigma(s) although I don't know if I should use an earlier version instead or if I even an upgrade them forward.

I would really love to make those changes, so please help me and I will send you the new files so you will also have the new languages too if you like it.

**Comment by AlejandroGarcia92** [comment]
@4truemodels contact me by email and I will explain you better in Spanish all what you have to do.
Contact: agarciamoreno@fundaciocim.org
