### ISSUE TITLE
Insert SD card

### ISSUE THREAD

**Issue by hst68** [BCN3D/BCN3DSigma-Firmware#164]
Since the firmware update 1.2.6 I get the message "Insert SD card" on the display when I insert the original bcn3d R17 SD card. Same with all other SD cards. Reset and restart failed.

**Comment by WanaGo** [comment]
This screen you mean?
![image](https://user-images.githubusercontent.com/759846/31633045-8c90f486-b31b-11e7-9fdf-0e417c6df142.png)

**Comment by hst68** [comment]
yes exactly

**Comment by WanaGo** [comment]
I would highly doubt its a firmware things - likely something has happened to your machine, you are best to contact sat@bcn3dtechnologies.com for support.
Have you had the centre panel out of the floor of your machine? Remove it and check the cable to the motherboard from the SD card is in place still, and look at the SD card circuit board, and make sure nothing looks out of place on that end. On my machine it has a 5V and 3.3V selection switch, it should be on 5V. Your machine may not have this, I am not sure if they changed it at any point.

**Comment by hst68** [comment]
The situation has been resolved. The problem was a defective SD card reader

**Comment by AlejandroGarcia92** [comment]
@hst68 ok
