### ISSUE TITLE
Warning! Full Calibration works not any more

### ISSUE THREAD

**Issue by hst68** [BCN3D/BCN3DSigma-Firmware#182]
**Warning! This bug can cause considerable damage if the printer is not switched off quickly.**

The Full Calibration works with the compiled

> v01-1.2.7RC_M01.05.hex

 [firmware 2 1.2.8](https://github.com/BCN3D/BCN3DSigma-Firmware/tree/v01-1.2.7RC?files=1) (it shows on the display) of not any more. Almost destroyed my glass bed and the switches. The leftist Hothend is better said to be banging against the right. So that the switch is outside the glass bed. The bed moves up the switch in the empty room, wants to drive back and hangs with the switch on the edge of the glass! And BANG ratter ratter ratter - emergency stop

the Firmware version (v01-1.2.7RC_M12.22.hex) [0 1.2.7 RC](https://github.com/BCN3D/BCN3DSigma-Firmware/wiki/1.2.7RC) works with full calibration

**Comment by AlejandroGarcia92** [comment]
Sorry, it was my fault. I compiled the Sigmax version. I've just reversed to M12.22. Anyway, when I update the RC version I do it in Releases.
