### ISSUE TITLE
01-1.2.7RC Unable to read files on SD

### ISSUE THREAD

**Issue by atlemo** [BCN3D/BCN3DSigma-Firmware#184]
Using the release from 10 days ago (commit 6732d9a) I'm unable to read any files on the SD card.
I can push a blank line and then it'll read on the next screen, but the list is empty in the beginning.

**Comment by AlejandroGarcia92** [comment]
Can you share me a video? Until now, I couldn't redo what you report.

**Comment by haqbany** [comment]
HI I have found this SD card formatter thats work great with Mac OSX and Windows very Simple. 
https://www.sdcard.org/downloads/formatter_4/

All the Best
