### ISSUE TITLE
change the filament during printing BUG

### ISSUE THREAD

**Issue by hst68** [BCN3D/BCN3DSigma-Firmware#190]
If you change the filament during printing (Pause ->Tools->Change Filament). If it happens repeatedly that the process ends while unloading, but the LCD screen gets stuck with the process window. Actually, he should go to Lade Filament Screen. That's annoying because every pressure is destroyed! Firmware 1.2.7 R17 bondtech extruder

**Comment by AlejandroGarcia92** [comment]
We had this issue with bondtech and we saw that the relation between steps/mm and max feedrate was too high for the microcontroller and we set the max feedrate of E motors to 40mm/s for Sigmax which works with bondtech(Sigma has set by default 60). 

Use the following commands:
M203 E40.00
M500

**Comment by hst68** [comment]
Great, it works!
