### ISSUE TITLE
Feature: Repeat Last Print

### ISSUE THREAD

**Issue by thesec** [BCN3D/BCN3DSigma-Firmware#192]
Being able to repeat the last print would be nice to have.

It could be 
- automatically displayed at the end of a print, followed by confirmation to do so and a confirmation to have cleaned the bed afterwards
- another option on top of the model selection when starting to browse the SD card
- either should name the model as listed in the SD card file's list, same as today with the print confirmation.

**Comment by AlejandroGarcia92** [comment]
#226
