### ISSUE TITLE
Sudden shift of the x-Axis

### ISSUE THREAD

**Issue by svengl** [BCN3D/BCN3DSigma-Firmware#193]
Another print, another failure

During print with the right extruder, the x-axis suddenly shifts. This threw off the whole build plate including the glass plate and resulted in a destroyed z-Axis end switch...! Some black plastic parts broke off.
This time Simplify3D was used due to bug https://github.com/BCN3D/Cura/issues/105 but I am pretty sure it is not a slicer issue.

![image005943](https://user-images.githubusercontent.com/22238455/41524847-53dc38e4-72ce-11e8-8e49-4924a803748a.jpg)
![image005956](https://user-images.githubusercontent.com/22238455/41524856-5d08f3bc-72ce-11e8-8e79-fdb8e191fa6b.jpg)
![image005981](https://user-images.githubusercontent.com/22238455/41524865-6908a784-72ce-11e8-8e75-be6751085bbe.jpg)
![image006128](https://user-images.githubusercontent.com/22238455/41524989-0574993e-72cf-11e8-922d-61bff3e3f2d3.jpg)
![image006149](https://user-images.githubusercontent.com/22238455/41524998-07e59de4-72cf-11e8-80bd-f0e7a134d049.jpg)
![image007237](https://user-images.githubusercontent.com/22238455/41525003-0ce4e692-72cf-11e8-899a-1cc2dea74fdd.jpg)

**Comment by AlejandroGarcia92** [comment]
It seems that X right motor stepper driver is losing steps.

**Comment by svengl** [comment]
So what can I do? We started another print with a new end switch and it works fine at the moment. 
Could a replacement of the stepper driver boards help? Or is that improbable? Or rather the mainboard?

**Comment by sennalb** [comment]
Hi,
I have the same problem with sigmax and the top trasparent cover, but if i remove the top cover the problem does not arise again.

I suppose that is temperature problem, I using the printer in my office with an ambient temperature of about 20-25 degrees. With the top cover the internal temperature of sigmax printer it seems too high: the bed is hot (65 deggres) the temperature of the motors of X axis is very very high.

My 2 cents
Alberto Senni
Studio Tecnico Zocca BO (Italy)

**Comment by AlejandroGarcia92** [comment]
Did you contact with support? They are dealing with those kind of issues.

**Comment by sennalb** [comment]
Yes, I am in contact with support
Thanks 
Alberto

**Comment by svengl** [comment]
Maybe a closing comment on this:
As somehow expected, it was not the SD Card reader (as suggested in https://github.com/BCN3D/BCN3DSigma-Firmware/issues/155) 
We sent the printer to our dealer and they found that the stepper driver voltage was set way too high, so they adjusted it. Further, the right stepper driver was exchanged as it was probably broken.
Now it seems to be running well for the time being.
