### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by axiiiofevil** [BCN3D/BCN3DSigma-Firmware#194]
Hi,

I can't seem to compile V 1.2.7.

[1.2.7-compile-errors.txt](https://github.com/BCN3D/BCN3DSigma-Firmware/files/2208177/1.2.7-compile-errors.txt)

Looks like a change to HardwareSerial.h??

**Comment by axiiiofevil** [comment]
I have changed the Configuration.h file to allow use of E3D hotends, but it won't compile with the standard Configuration.h file either...

**Comment by axiiiofevil** [comment]
Using Arduino 1.8.5 by the way.

**Comment by axiiiofevil** [comment]
I can compile V 1.2.6.

**Comment by AlejandroGarcia92** [comment]
Yes, you need to change HardwareSerial.h. I've just attached here.
[HardwareSerial.zip](https://github.com/BCN3D/BCN3DSigma-Firmware/files/2213077/HardwareSerial.zip)
