### ISSUE TITLE
Can't Compile    who can tell me why

### ISSUE THREAD

**Issue by crazyp1g** [BCN3D/BCN3DSigma-Firmware#195]
Arduino:1.8.5 (Windows Store 1.8.10.0) (Windows 10), 开发板："Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\Hysteresis.cpp:27:0:

sketch\language.h:109:25: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                         ^

sketch\language.h:109:60: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                                                            ^

In file included from sketch\LCD_FSM.h:23:0,

                 from sketch\LCD_FSM.cpp:6:

sketch\language.h:109:25: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                         ^

sketch\language.h:109:60: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                                                            ^

sketch\LCD_FSM.cpp: In function 'void lcd_fsm_lcd_input_logic()':

sketch\LCD_FSM.cpp:445:70: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

    genie.WriteStr(STRING_UTILITIES_FILAMENT_CHANGEFILAMENT_TEMPS,"0%");

                                                                      ^

sketch\LCD_FSM.cpp:701:70: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

    genie.WriteStr(STRING_UTILITIES_FILAMENT_CHANGEFILAMENT_TEMPS,"0%");

                                                                      ^

sketch\LCD_FSM.cpp:1636:71: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(STRING_UTILITIES_FILAMENT_CHANGEFILAMENT_TEMPS,"0%");

                                                                       ^

sketch\LCD_FSM.cpp:1999:70: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

    genie.WriteStr(STRING_UTILITIES_FILAMENT_CHANGEFILAMENT_TEMPS,"0%");

                                                                      ^

sketch\LCD_FSM.cpp:2115:72: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_UTILITIES_FILAMENT_CHANGEFILAMENT_TEMPS,"0%");

                                                                        ^

sketch\LCD_FSM.cpp:2403:70: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

    genie.WriteStr(STRING_UTILITIES_FILAMENT_CHANGEFILAMENT_TEMPS,"0%");

                                                                      ^

sketch\LCD_FSM.cpp: In function 'void ListFilesParsingProcedure(int, int)':

sketch\LCD_FSM.cpp:5599:48: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

    genie.WriteStr(stringfiledur[jint],"       ");//Printing form

                                                ^

sketch\LCD_FSM.cpp: In function 'void ListFilesUpfunc()':

sketch\LCD_FSM.cpp:5643:52: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(stringfilename[jint],"        ");//Printing form

                                                    ^

sketch\LCD_FSM.cpp:5644:54: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(stringfiledur[jint],"           ");//Printing form

                                                      ^

sketch\LCD_FSM.cpp: In function 'void ListFilesDownfunc()':

sketch\LCD_FSM.cpp:5685:52: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(stringfilename[jint],"        ");//Printing form

                                                    ^

sketch\LCD_FSM.cpp:5686:54: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(stringfiledur[jint],"           ");//Printing form

                                                      ^

sketch\LCD_FSM.cpp: In function 'void ListFileListINITSD()':

sketch\LCD_FSM.cpp:5727:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(stringfilename[jint],"        ");//Printing form

                                                   ^

sketch\LCD_FSM.cpp:5728:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(stringfiledur[jint],"           ");//Printing form

                                                     ^

sketch\LCD_FSM.cpp: In function 'void ListFileListENTERBACKFORLDERSD()':

sketch\LCD_FSM.cpp:5905:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(stringfilename[jint],"        ");//Printing form

                                                   ^

sketch\LCD_FSM.cpp:5906:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(stringfiledur[jint],"           ");//Printing form

                                                     ^

In file included from sketch\Marlin_main.cpp:52:0:

sketch\language.h:109:25: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                         ^

sketch\language.h:109:60: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                                                            ^

In file included from sketch\Marlin_main.cpp:61:0:

sketch\macros.h:93:0: warning: "STRINGIFY_" redefined

 #define STRINGIFY_(M) #M

 ^

In file included from sketch\Marlin_main.cpp:52:0:

sketch\language.h:67:0: note: this is the location of the previous definition

 #define STRINGIFY_(n) #n

 ^

In file included from sketch\Marlin_main.cpp:61:0:

sketch\macros.h:94:0: warning: "STRINGIFY" redefined

 #define STRINGIFY(M) STRINGIFY_(M)

 ^

In file included from sketch\Marlin_main.cpp:52:0:

sketch\language.h:68:0: note: this is the location of the previous definition

 #define STRINGIFY(n) STRINGIFY_(n)

 ^

In file included from sketch\Marlin_main.cpp:58:0:

sketch\LCD_Handler.h: In function 'void myGenieEventHandler()':

sketch\LCD_Handler.h:107:57: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_INFO_UI_SERIALID,UI_SerialID);

                                                         ^

sketch\Marlin_main.cpp: In function 'bool touchscreen_init()':

sketch\Marlin_main.cpp:1105:60: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

    genie.WriteStr(STRING_INIT_FIRWAREVERSION,VERSION_STRING);

                                                            ^

In file included from sketch\cardreader.cpp:12:0:

sketch\language.h:109:25: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                         ^

sketch\language.h:109:60: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                                                            ^

In file included from sketch\planner.cpp:59:0:

sketch\language.h:109:25: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                         ^

sketch\language.h:109:60: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                                                            ^

In file included from sketch\stepper.cpp:29:0:

sketch\language.h:109:25: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                         ^

sketch\language.h:109:60: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]

 #define MSG_M115_REPORT "FIRMWARE_NAME:Marlin "MACHINE_NAME"; FIRMWARE_VERSION:"VERSION_STRING"; FIRMWARE_URL:" FIRMWARE_URL "; PROTOCOL_VERSION:" PROTOCOL_VERSION "; MACHINE_TYPE:" MACHINE_NAME "; EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "; UUID:"

                                                            ^

sketch\stepper.cpp: In function 'void display_check_rx()':

sketch\stepper.cpp:182:18: note: #pragma message: Hardware Serial must not have any protected variables or this will not work! Modify HardwareSerial.h to be public!

  #pragma message "Hardware Serial must not have any protected variables or this will not work! Modify HardwareSerial.h to be public!"

                  ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:98:30: error: 'volatile uint8_t* const HardwareSerial::_ucsra' is protected

     volatile uint8_t * const _ucsra;

                              ^

In file included from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from sketch\Marlin.h:20,

                 from sketch\stepper.cpp:24:

stepper.cpp:184: error: within this context

  if (bit_is_set(*MYSERIAL_SCREEN._ucsra, 7)) {

                                  ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:98:30: error: 'volatile uint8_t* const HardwareSerial::_ucsra' is protected

     volatile uint8_t * const _ucsra;

                              ^

In file included from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from sketch\Marlin.h:20,

                 from sketch\stepper.cpp:24:

stepper.cpp:185: error: within this context

   if (bit_is_clear(*MYSERIAL_SCREEN._ucsra, UPE0)) {

                                     ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:101:30: error: 'volatile uint8_t* const HardwareSerial::_udr' is protected

     volatile uint8_t * const _udr;

                              ^

stepper.cpp:188: error: within this context

    unsigned char c = *MYSERIAL_SCREEN._udr;

                                       ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:105:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_head' is protected

     volatile rx_buffer_index_t _rx_buffer_head;

                                ^

stepper.cpp:189: error: within this context

    rx_buffer_index_t i = (unsigned int)(MYSERIAL_SCREEN._rx_buffer_head + 1) % SERIAL_RX_BUFFER_SIZE;

                                                         ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:106:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_tail' is protected

     volatile rx_buffer_index_t _rx_buffer_tail;

                                ^

stepper.cpp:195: error: within this context

    if (i != MYSERIAL_SCREEN._rx_buffer_tail) {

                             ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:113:51: error: 'unsigned char HardwareSerial::_rx_buffer [64]' is protected

     unsigned char _rx_buffer[SERIAL_RX_BUFFER_SIZE];

                                                   ^

stepper.cpp:196: error: within this context

     MYSERIAL_SCREEN._rx_buffer[MYSERIAL_SCREEN._rx_buffer_head] = c;

                     ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:105:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_head' is protected

     volatile rx_buffer_index_t _rx_buffer_head;

                                ^

stepper.cpp:196: error: within this context

     MYSERIAL_SCREEN._rx_buffer[MYSERIAL_SCREEN._rx_buffer_head] = c;

                                                ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:105:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_head' is protected

     volatile rx_buffer_index_t _rx_buffer_head;

                                ^

stepper.cpp:197: error: within this context

     MYSERIAL_SCREEN._rx_buffer_head = i;

                     ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:101:30: error: 'volatile uint8_t* const HardwareSerial::_udr' is protected

     volatile uint8_t * const _udr;

                              ^

stepper.cpp:201: error: within this context

    *MYSERIAL_SCREEN._udr;

                     ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:98:30: error: 'volatile uint8_t* const HardwareSerial::_ucsra' is protected

     volatile uint8_t * const _ucsra;

                              ^

In file included from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from sketch\Marlin.h:20,

                 from sketch\stepper.cpp:24:

stepper.cpp:204: error: within this context

  if (bit_is_set(*MYSERIAL._ucsra, 7)) {

                           ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:98:30: error: 'volatile uint8_t* const HardwareSerial::_ucsra' is protected

     volatile uint8_t * const _ucsra;

                              ^

In file included from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files\windowsapps\arduinollc.arduinoide_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from sketch\Marlin.h:20,

                 from sketch\stepper.cpp:24:

stepper.cpp:205: error: within this context

   if (bit_is_clear(*MYSERIAL._ucsra, UPE0)) {

                              ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:101:30: error: 'volatile uint8_t* const HardwareSerial::_udr' is protected

     volatile uint8_t * const _udr;

                              ^

stepper.cpp:208: error: within this context

    unsigned char c = *MYSERIAL._udr;

                                ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:105:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_head' is protected

     volatile rx_buffer_index_t _rx_buffer_head;

                                ^

stepper.cpp:209: error: within this context

    rx_buffer_index_t i = (unsigned int)(MYSERIAL._rx_buffer_head + 1) % SERIAL_RX_BUFFER_SIZE;

                                                  ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:106:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_tail' is protected

     volatile rx_buffer_index_t _rx_buffer_tail;

                                ^

stepper.cpp:215: error: within this context

    if (i != MYSERIAL._rx_buffer_tail) {

                      ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:113:51: error: 'unsigned char HardwareSerial::_rx_buffer [64]' is protected

     unsigned char _rx_buffer[SERIAL_RX_BUFFER_SIZE];

                                                   ^

stepper.cpp:216: error: within this context

     MYSERIAL._rx_buffer[MYSERIAL._rx_buffer_head] = c;

              ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:105:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_head' is protected

     volatile rx_buffer_index_t _rx_buffer_head;

                                ^

stepper.cpp:216: error: within this context

     MYSERIAL._rx_buffer[MYSERIAL._rx_buffer_head] = c;

                                  ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:105:32: error: 'volatile rx_buffer_index_t HardwareSerial::_rx_buffer_head' is protected

     volatile rx_buffer_index_t _rx_buffer_head;

                                ^

stepper.cpp:217: error: within this context

     MYSERIAL._rx_buffer_head = i;

              ^

In file included from C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:232:0,

                 from sketch\genieArduino.h:49,

                 from sketch\Marlin.h:30,

                 from sketch\stepper.cpp:24:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h:101:30: error: 'volatile uint8_t* const HardwareSerial::_udr' is protected

     volatile uint8_t * const _udr;

                              ^

stepper.cpp:221: error: within this context

    *MYSERIAL._udr;

              ^

exit status 1
within this context

在文件 -> 首选项开启
“编译过程中显示详细输出”选项
这份报告会包含更多信息。
 what's the matter？

**Comment by crazyp1g** [comment]
i just download and no any modify

**Comment by dvb-adenin** [comment]
that's why:
```
sketch\stepper.cpp:182:18: note: #pragma message: Hardware Serial must not have any protected variables or this will not work! Modify HardwareSerial.h to be public!
```
solution:
edit **C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/HardwareSerial.h**
search this :
```
class HardwareSerial : public Stream
{
  protected:
```
change **protected:** to **public:**

looks somewhat brutal, but it works
