### ISSUE TITLE
Cura not connecting to printer. 

### ISSUE THREAD

**Issue by Lostinthe907** [BCN3D/BCN3DSigma-Firmware#199]
I am having this issue, i did the last update to firmware 1.2.7 and cura is up to date 2.1.0 and it is not connecting to the printer to upgrade the firmware even though it says its connected. it just sits and says connecting... 

any help to upgrade it to the new firmware not using cura or another way would be awesome

Thanks! 
![broke](https://user-images.githubusercontent.com/20216867/45910262-2b1ec580-bdb4-11e8-88e5-d55c16b7ac48.png)

**Comment by Lostinthe907** [comment]
Update, 

I have reinstalled cura 2.0.2 and have tried with the same issue. i now believe it is a fault in my firmware not allowing it to connect.

**Comment by Lostinthe907** [comment]
fixed!! 
Issue was the port number. When plugged into usb it was claiming COM5. renamed COM5 to COM6 and it was able to connect through Cura.

**Comment by AlejandroGarcia92** [comment]
Perfect!
