### ISSUE TITLE
How to Calibrate with other material than PLA?

### ISSUE THREAD

**Issue by pgilfernandez** [BCN3D/BCN3DSigma-Firmware#202]
I thought this new 2.0.2 firmware let the option to choose the temperature of your materials in order to launch the calibration process but I don't see it...

How can it be done?
Thanks

**Comment by AlejandroGarcia92** [comment]
The temperatures have been chosen depending of the material that you loaded on "Load Filament". 

Also, at Main Menu/Temperatures you will see the temperatures set.

If you want to use another temperatures that are not the default ones, use the option "Custom" at "Load Filament".

2.0.3 FW has been released btw.
