### ISSUE TITLE
Display Fw missing "Botton"s

### ISSUE THREAD

**Issue by thesec** [BCN3D/BCN3DSigma-Firmware#204]
Workshop4 IDE does not open the .4dgenie project file for a ton of 'Botton's claimed missing, e.g.
![screenshot 2018-10-19 at 19 41 08](https://user-images.githubusercontent.com/91770/47234810-50184f80-d3d7-11e8-96b8-73add9b8c4b3.png)

**Comment by thesec** [comment]
Updating the IDE to the latest - 4.5.0.17b - ... just stalls the IDE :/

**Comment by thesec** [comment]
Finally stumbled across the "Read.txt" in "ExtraFiles" and got to find the location described by "*\4D Labs\4D Workshop 4 IDE\SysImages\Buttons".

I suggest to include instead the absolute path as Windows users rarely install on other paths and only the drive letter should change if they do.
Moving the ReadMe next to the Genie file will help others to find it more quickly.

**Comment by AlejandroGarcia92** [comment]
Ok, I will take into account your suggestions.
