### ISSUE TITLE
Compilation Settings Display FW

### ISSUE THREAD

**Issue by thesec** [BCN3D/BCN3DSigma-Firmware#209]
Which Project/Destination settings in the Workshop 4 IDE are the correct ones to compile the same as provided within the repository?
"Run RAM", "Run Flash" or "uSD" and which Bank?
Which do you use to bootstrap the displays for R19's?

**Comment by thesec** [comment]
Just tried:
"No Errors, code size = 0 bytes
Starting Script LOADSIGMA.4dscript
Ending Script LOADSIGMA.4dscript"
is what happens without anything loaded to the display, at least it does not reset as I'd expect it to? The com port is the one reported by "mode" and in the IDE.
Is there anything else to be set, configured, ...?

**Comment by AlejandroGarcia92** [comment]
Don't open LOADSIGMA.4dscript, use the Temp4D.4dg.
 You will see something like that: 

I pressed compile

![captura 1](https://user-images.githubusercontent.com/17469944/47987793-bfcd5080-e0e0-11e8-903d-b4c907590365.jpg)


![captura 2](https://user-images.githubusercontent.com/17469944/47987800-c22faa80-e0e0-11e8-95c4-940f184ab107.jpg)

![captura 3](https://user-images.githubusercontent.com/17469944/47988200-e63fbb80-e0e1-11e8-94ef-23a1dd648462.jpg)

**Comment by thesec** [comment]
Thanks again, hope to get to give it a try next weekend ...

**Comment by thesec** [comment]
Yay - that worked! Thanks @AlejandroGarcia92 👍
