### ISSUE TITLE
[Bug] R16 Unable to print from SD 

### ISSUE THREAD

**Issue by pvnct** [BCN3D/BCN3DSigma-Firmware#210]
After upgrading my R16 to the latest firmware 2.0.4 (and the screen sd card of course) i am unable to print from SD card: 

All files appears in the browser but when i hit print it reload the browser and don't launch the print. 

I have tried  with different  SD cards, different codes from BCN3D cura or S3D , same result

**Comment by AlejandroGarcia92** [comment]
I discard mainboard FW cause of course and I think that something is failing during lcd fw upgrade. Historically there were some issues around the sd card but I'm not sure what is happening right now without more extra feedback.

**Comment by AlejandroGarcia92** [comment]
Any way, can you tell us which sd card do you have placed on the LCD? Because we had some problems with the sd card that are not industrial, and those are what we are providing right now on all our products(Printers and Upgrade kid R19).

If you can take a picture, I will be glad.

**Comment by pvnct** [comment]
The Screen SD has been provided by BCN3D - You / your team already replaced the original one i got with the  machine. 
I remember from the last failed update that it is a Toshiba (red and grey-white) but i will take a pic as soon as i return to my office. 
Also i have to say that i didn't try to format the screen sd  to FAT16 (if i remember well) when i tried to update to 2.0.4 
Perhaps it can helps

But what is weird is that the only thing not working were launch print. Alternatively i have noticed a faster file browsing and maybe also a faster start  - new features like extruder setup (bondtech) - or even the led dimming

**Comment by pvnct** [comment]
![img_20181119_100324](https://user-images.githubusercontent.com/22561965/48697245-7d2d6d00-ebe4-11e8-992f-dfd11195b10a.jpg)

**Comment by AlejandroGarcia92** [comment]
It is not a good sd card. Can you try to format the sd anyway?

**Comment by pvnct** [comment]
FAT16 ? as previous fw version ?

**Comment by AlejandroGarcia92** [comment]
Yes FAT16 for the LCD
