### ISSUE TITLE
flag/register access is wrong

### ISSUE THREAD

**Issue by dvb-adenin** [BCN3D/BCN3DSigma-Firmware#214]
https://github.com/BCN3D/BCN3DSigma-Firmware/blob/v01-2.0.6/Marlin/LCD_FSM.cpp#L922
flag_utilities_filament_register_acceptok is not a member of flag_sdprinting_register

**Comment by AlejandroGarcia92** [comment]
Ok, I think that it is not causing a bug, fortunately.

**Comment by AlejandroGarcia92** [comment]
Fixed
