### ISSUE TITLE
Stuck in Calibration

### ISSUE THREAD

**Issue by thesec** [BCN3D/BCN3DSigma-Firmware#218]
Leaving the Sigma in the left Z-calibration I got distracted a few minutes ... and found the printer having printed the calibration mesh but also having automatically allowed himself to return to the main menu.
Restarting the calibration it starts again with the left Z-calibration but also returns to the main menu right afterwards. A cold restart - turning power off and back on - of the printer did not help.

How to get out of this loop?

Firmware in use is 2.07.

**Comment by thesec** [comment]
Keeps doing the same after an update to 2.08 ... and ... also after a 'factory reset' using M502 ... :/

The prompt to select one of the five printed lines shows up for a blink and is immediately replaced by the main menu.

**Comment by thesec** [comment]
Keeps showing up after bootstrapping the board ... wtf :#

**Comment by fjohannes** [comment]
Had the same issue with v01-208 firmware twice, but luckily after cold restart it worked again.

**Comment by AlejandroGarcia92** [comment]
Hi, you did a good description of the issue but it sounds very rare. Maybe, the element that it's not working is the LCD screen. That's the only idea that I have in mind at the moment. So, SD card format could be enough but I'm not sure.

**Comment by thesec** [comment]
Thanks Alejandro, already been under way in that direction having checked the SD to sit properly and the cables to do so, too. Will add a reformatting ...
