### ISSUE TITLE
Smartpurge M800 does not work

### ISSUE THREAD

**Issue by mfreda** [BCN3D/BCN3DSigma-Firmware#219]
Hi, I tested M800 command: M800 F48 S0.0003 E15.25 P3
Smartpurge function return always (after tool switch):

READ: Purge distance
READ: 3.00
READ: Time inactive
READ: 0

Analysing the code (version 2.0.8), I noticed that variable time_inactive_extruder[0|1] is never incremented.

Best Regards.

Mario Freda.

**Comment by AlejandroGarcia92** [comment]
Let me check it.

**Comment by AlejandroGarcia92** [comment]
I've seen that this feature is implemented only for SD printing.

**Comment by mfreda** [comment]
Ok, where the variabile time_inactive_extruder[0|1] is incremented in source code Marlin_main.cpp?

In the old versions was incremented in display loop. In the new version I cannot found where is incremented.

Thank you very much.

Mario Freda.

**Comment by UBGL** [comment]
@AlejandroGarcia92

Is it possible to make it in serial printing available?

**Comment by AlejandroGarcia92** [comment]
Yes, it is.
