### ISSUE TITLE
No Filament runout detection during a SD print job

### ISSUE THREAD

**Issue by mfreda** [BCN3D/BCN3DSigma-Firmware#222]
Hi I have Sigma R19 with firmware 2.0.8.

At Filament runout the printer doesn't stop and continue printing without filament.

Is a hardware issue or a firmware issue?

The printer is new.

Thank you.

Mario Freda.

**Comment by AlejandroGarcia92** [comment]
If the functionality is not disabled at printer setup, it is a hardware issue.

**Comment by mfreda** [comment]
Ok, I have solved myself, there was a switch defect that I solved.

Thanks.
