### ISSUE TITLE
BCNSigma R17 LCD download zip corrupt.

### ISSUE THREAD

**Issue by svenedt** [BCN3D/BCN3DSigma-Firmware#224]
https://github.com/BCN3D/BCN3DSigma-Firmware/blob/master/SD.files.v202-LCD-SIGMA-R17-R19.zip

Zip File seems corrupted. Can anyone else confirm?

**Comment by AlejandroGarcia92** [comment]
Have you downloaded the repository?

**Comment by WanaGo** [comment]
Zip works fine for me

**Comment by svenedt** [comment]
Thanks. Tried the repo directly instead of just the folders
