### ISSUE TITLE
Algunas Sugerencias

### ISSUE THREAD

**Issue by 4truemodels** [BCN3D/BCN3DSigma-Firmware#3]
Esto realmente no es un "issue", así que si consideráis que éste no es el lugar para éste tipo de comentarios podemos moverlo o eliminarlo, lo que deseéis.

Se trata de sugeriros que en el "display" pueda aparecer el tiempo de impresión, monitorizar el tiempo de trabajo de la SIGMA (como de cualquier otra máquina) me parece imprescindible, así que como petición os diría que se mostrase en pantalla el tiempo de impresión, tanto durante la misma como al completarse.

También hecho de menos no poder ordenar a la máquina un desplazamiento por pasos (10.0, 1.0 y 0.1 mm) para cada Eje, como sí puede hacerse con la BCN3D+, y así poder realizar ciertos diagnósticos.

Finalmente, durante el proceso de introducción de Temperaturas, el hecho de no poder introducir más que 5 grados por cada pulsación como máximo lo hace un poco tedioso, quizás cambiar el comando para que el cambio vaya de 10 en 10 (dejando el otro tal y como está en 1 por pulsación) podría ser de agradecer.

Como véis esto no tiene nada de "issue", sólo son ideas sobre detalles menores que no tienen relevancia sobre el funcionamiento práctico de la máquina.
Sea como sea... ¡Muchas gracias por vuestra atención!

PD: ¿alguna preferencia sobre el idioma en el que comunicarse por este medio? No tengo inconveniente en escribir ni en Castellano, Català (mi lengua materna) o Inglés.

**Comment by kitusmark** [comment]
Hola @4truemodels,

Hemos registrado todo lo que nos comentas y lo procesaremos con el equipo.
Es cierto que la interfaz de la máquina ha cambiado mucho y la manera de interactuar con ella es diferente. Piensa que la máquina está pensada para un cliente final que puede no haber tenido experiencia con una impresora 3D previamente. 
Nosotros al principio también echabamos de menos las características que comentas pero luego hemos visto que se vuelven prescindibles para un porcentaje muy alto de los usuarios.

De todas maneras estamos trabajando en ello y dependiendo de lo que nos digan los clientes, evolucionaremos en ese aspecto.

Un saludo.

En castellano o inglés a nosotros nos va perfecto!
