### ISSUE TITLE
Left Z high leveling print test is misaligned

### ISSUE THREAD

**Issue by pgilfernandez** [BCN3D/BCN3DSigma-Firmware#36]
You can easily check it on the next picture:
![img_2697](https://cloud.githubusercontent.com/assets/5942369/12445019/43309660-bf62-11e5-88c8-ed5f04559916.jpg)
The red one is the left Z test and from 1 to 5 it shifts to the bottom while the white one, right Z test, is correctly drawn.

**Comment by kitusmark** [comment]
Hi @pgilfernandez. Is it fixed with the new firmware Release? v1.1.4? 

If it's fixed please close the issue. 

Thanks.

**Comment by mrcg** [comment]
My Sigma is loosing all EEPROM varialbles when switched off for longer time.
All calibration data and filament temperatures are impacted.
When data are lost the 1st full calibration looks also like shown in the picture.
2nd calibration (when data are not lost) calibration pattern are printed correctly.

@pgilfernandez : Do you experience also loss of calibration data from time to time?

If yes please report output from M503 if you still have the issue.
