### ISSUE TITLE
Feature Request: Option to print GCode from 2nd (right) extruder

### ISSUE THREAD

**Issue by mrcg** [BCN3D/BCN3DSigma-Firmware#39]
I would like to have option for single mode when loading GCode from SD to print from the 2nd (right) extruder. As workaround "T1" command can be added to the very first line of the GCode but unfortunately nozzle fan control is not working on 2nd extruder.

Would be great to have such feature. Should be no big thing but VERY USEFUL !!!!

**Comment by kitusmark** [comment]
Hi @mrcg.

Yeah, it will be such a simple but useful feature. Actually we do the same as you, write a T1 at the top of the Gcode file. 
What do you mean by _"nozzle fan control is not working on the 2nd extruder"_ ?
