### ISSUE TITLE
Errores al Cargar Filamento

### ISSUE THREAD

**Issue by 4truemodels** [BCN3D/BCN3DSigma-Firmware#4]
Saludos,

Esta vez quería comentaros otro problema que estoy experimentando...
Se trata de algo que sucede ocasionalmente durante el proceso de cargar el filamento en cualquiera de los dos extrusores... y es que justo cuando empieza a recoger el filamento el sistema parece fallar y, o bien se reinicia la SIGMA, o bien se queda como bloqueada mostrando el mensaje "processing...", pero sin hacer nada y es necesario apagarla y volverla a encender para restablecerlo todo.

No sé si es algo que sólo me sucede a mí, o se trata de un error más frecuente.
Gracias por vuestro trabajo.

**Comment by flandaluce** [comment]
Me ha pasado varias veces el mismo problema
