### ISSUE TITLE
[Issue] No return to home after stop print

### ISSUE THREAD

**Issue by Zorgonaute84** [BCN3D/BCN3DSigma-Firmware#43]
I noticed that the extruder are not return to home systematically when I cancelled a print. I saw that during the right extruder printing.

Same thing, please add a return to home for both extruder before each print. I launch a print but I let my right extruder in the middle, and the left extruder start printing and collides the right one.

New printer with firmware version : 1.1.3

**Comment by kitusmark** [comment]
Hi @Zorgonaute84 

It's solved with the new firmware release (1.1.4)?  If so please close the issue. 

Thanks!

**Comment by Zorgonaute84** [comment]
Ok, I'll check that. Thanks !!
