### ISSUE TITLE
[Enhancement] Noise reduction

### ISSUE THREAD

**Issue by Zorgonaute84** [BCN3D/BCN3DSigma-Firmware#48]
In this ticket I want to share you a tips to reduce the noise of the sigma and an engancement request.

About the request, is it possible to activate the heated head fan only when the nozzle is heating or cooling ? For maintenance, it's intersting to power on the sigma just for activate the light system and the fan noise is anoying and useless.

About the tips. I significantly reduce the noise during printing by glue with a heated glue pistol the edges (inside) of the two container bellow the heads. It's reduce the vibration and the noise.

**Comment by mrcg** [comment]
+1

* NTC fan control for the extruder fan. If it's not used it should be off or very low rotation
* Isolate fan with rubber/bumper from metallic housing

The high noise level is really something what needs to be improved on the Sigma.

**Comment by Zorgonaute84** [comment]
I significatly reduced the noise of my Sigma with hot glue gun !

First, I harden the two waste container by adding some glue into each edges of the container. It's stopped any vibration...

Secondly I totally disassembled my 2 heads and I had some glue too into each edges of the 2 metal plates (inside)

Then I cuted small circles (2mm) in the cold glue tube, and I inserted them between the 2 feeder motor and the metal frame to reduce the pervasion of the motor vibration into the frame.

And finally I isolated the middle blue plastic part than the others with felt.

**Comment by pgilfernandez** [comment]
@Zorgonaute84 could you share some pictures?

Thank you!

**Comment by Zorgonaute84** [comment]
Yes of course. I will take some picture this evening.

**Comment by kitusmark** [comment]
We'd love to see those pictures too!

**Comment by Zorgonaute84** [comment]
So, you can find some pictures of the hack I dit on my Sigma.

You can see the different place where I added some hot glue (no visible too much because the glue is inside) You can see what I cutted to place between the feeder motor and the metal frame, and finally the felt used to isolated the blue part.
![img_7734](https://cloud.githubusercontent.com/assets/13313177/13285330/4dc9d128-dafa-11e5-8f64-c4da1a36609f.JPG)
![img_7735](https://cloud.githubusercontent.com/assets/13313177/13285331/4de498d2-dafa-11e5-9698-de5fa6ea3458.JPG)
![img_7736](https://cloud.githubusercontent.com/assets/13313177/13285332/4deb6cf2-dafa-11e5-9909-bdca7b23fb4f.JPG)
![img_7740](https://cloud.githubusercontent.com/assets/13313177/13285333/4df07ae4-dafa-11e5-9391-c555a77aad99.JPG)
![img_7741](https://cloud.githubusercontent.com/assets/13313177/13285334/4df07e9a-dafa-11e5-939e-d33bc858e36f.JPG)
![img_7743](https://cloud.githubusercontent.com/assets/13313177/13285335/4df284f6-dafa-11e5-9bea-bb04ad74752a.JPG)
![img_7744](https://cloud.githubusercontent.com/assets/13313177/13285336/4df44ad4-dafa-11e5-80c4-dbaf665c71e7.JPG)

**Comment by pgilfernandez** [comment]
Thank you very much!
As I see, the noise produced by the rotating fans is not due to the fan case and the metal case, but on the bended parts of the metal hotend housing... is that right?

**Comment by Zorgonaute84** [comment]
I can't answer you exactly because I can't heard the sound of your Sigma. I had 2 differents Sigma, and each one produced different sounds. The first one was globally quiter than my actual , but the fans were much noisy. 

The only things that I can tell you with certitude is that most of the noise produced by my actual Sigma was caused by the vibration of the different bendeded parts. So you are right...

**Comment by pgilfernandez** [comment]
Ok, thanks for the comment.
I will check mine and try to fight the noise =)

Pablo Gil Fernández
email:
Twitter:
pgilfernandez@gmail.com
@exkr

2016-02-24 14:07 GMT+01:00 Zorgonaute84 <notifications@github.com>:

**Comment by kapetanikolas** [comment]
Hi I added a astrosyn nema 17 vibration damper on the Y axis motor and it does make a big difference on the noise. it sounds much more smooth now. Will try it on the Z axis to reduce noise during retraction Z-hop.  I will try to modify some other dampers to fit the nema 14s on the X axis 
On this topic i would like to ask if anyone thinks that the DRV8825 drivers are making the motors more noisy. I used DRV8825 on another printer and made the same high pitch noise along with high vibration compared to A4988. any thoughts?

**Comment by pgilfernandez** [comment]
I have done the fixes suggested by Zorgonaute84 and they have really
reduced the noise on my Sigma.
Thanks!

Pablo Gil Fernández
email:
Twitter:
pgilfernandez@gmail.com
@exkr

2016-02-29 2:48 GMT+01:00 kapetanikolas <notifications@github.com>:

**Comment by Zorgonaute84** [comment]
Happy to Heard that.

I Will have a look in the Astrosyn Dumper too, thanks to share your tips.

BCN3D, when you will open a real forum (in english) to share this kind of tips and tricks ? I dont think that Github is the right place for that, but it's the only place to share between Sigma owners (and the S3D forum too)

**Comment by kitusmark** [comment]
A lot of cool ideas arround here! The astrosyn dampeners are the key to solve the problem but a little bit expensive. We'll buy some and try them out. 

I found a replica on [thingiverse ](http://www.thingiverse.com/thing:664281)! 

About the forum... I don't think it's going to happen. We use to have one and didn't work out very well. Instead what we're looking is some people start communities @ [Google+](http://www.thingiverse.com/thing:664281) sharing their experiences. I think it's a good way to explain your work and development. 

What do you think?

**Comment by mrcg** [comment]
All bigger 3d printer manufacture have their own. Even for my first K8200 the vendor has managed to have own forum. It was very useful to exchange findings and recommendations. Nowadays it should be not a big thing to setup own forum. All this useful informations should be shared between the users. Github in not the right forum, but unfortunately the only available.

**Comment by pgilfernandez** [comment]
I do agree with you guys.
Marc, BCN3D Technologies should think again about a new forum site, maybe
the problem wasn't the low user activity but the bad user experience the
old forum had (I remember it and was hard to use...).
Please, give it a new opportunity.
=)

Pablo Gil Fernández
email:
Twitter:
pgilfernandez@gmail.com
@exkr

2016-02-29 22:50 GMT+01:00 mrcg <notifications@github.com>:

**Comment by kapetanikolas** [comment]
I will have to agree with you guys. a forum is essential 
by the way i am selling astrosyn dampers and for sigma users ill send them at cost £5 if you get them from my site(https://emvioeng.com/shop/product-category/3d-printing/) just send a msg saying you have a sigma. Lest create a a kickass community to support each other  as the machine really has the potential to become SUPER!

**Comment by Zorgonaute84** [comment]
Sure a forum is a must have. Maybe the old one was not a success because they wasn't Sigma section and the forum was mainly in Spanish !

**Comment by rogeruceda** [comment]
Hi!

I am Roger from BCN3D, we will have a forum in our new website probably in 2-3 weeks. We are still fixing some things in the web. BTW do you like it?

Thanks for all this improvements. I am surprised in how fast people is improving the Sigma!

Regards

**Comment by kapetanikolas** [comment]
hi guys
I like the new site a lot! and I am glad to read that you are planning a forum! 
I made a video of the noise reduction when a damper is added on the Y axis nema 17. https://www.youtube.com/watch?v=2gO24uwA1qU the first part is with the damper and the second without. keep you mouse on 5:50 and then press press 4 on you keyboard which should take you at 2:26. so you can go back and forth on the video to compare the noise.
I am planning to adapt the nema 17 dampers to fit the X nema14 motors. as soon as i have more ill report back

**Comment by Zorgonaute84** [comment]
Yeah, really good new site ! But you've got some display and scrolling troubles.

**Comment by rogeruceda** [comment]
Yes! We are still working on some issues

**Comment by 4truemodels** [comment]
Thx a lot Zorgonaute84 for sharing those tricks!
I will make my move next week in order to reduce noise level.
I'm not sure of have understood the use of dumpers kapetanikolas but I'll see further on that too.

I really like the new website design! Good work!

**Comment by rogeruceda** [comment]
We will test the dumpers next week!

**Comment by kapetanikolas** [comment]
Chris Lee has started a Sigma community for anyone who wants to join. https://plus.google.com/communities/100884192172984515424

ill be working on nema 14 vibration dampers this weekend in Bristol and try them on Monday.
The dampers on the Y axis reduced the high pitch noise and created a smoother sound.

Also tried my pop up enclosure last night...

![imag0466](https://cloud.githubusercontent.com/assets/7797828/13547160/26d772e8-e2be-11e5-8ed2-03c17c97ae0c.jpg)

**Comment by rogeruceda** [comment]
OMG this is porn! :p

**Comment by rogeruceda** [comment]
Hi guys,

We already have the forum in our website. Is still under construction buy you can start using it and giving us feedback.

Thanks!

https://www.bcn3dtechnologies.com/en/forums/forum/hardware/bcn3d-sigma/

**Comment by AlejandroGarcia92** [comment]
We improved our stepper drivers to make less noisy the machine.

More info: https://www.bcn3dtechnologies.com/en/catalog/stepper-drivers-upgrade-kit/

**Comment by pgilfernandez** [comment]
Hi Alejandro! Could you evaluate the noise reduction as a percentage? 50%, 60%...?

Thank you
