### ISSUE TITLE
Rotura de Filamento

### ISSUE THREAD

**Issue by 4truemodels** [BCN3D/BCN3DSigma-Firmware#5]
Saludos,

Esta vez quería comentar lo que me ha sucedido en no pocas ocasiones, y se trata de que el filamento (por ahora sólo he probado el PLA de Colorfila) se rompe durante la carga o retirada del mismo, con las consecuencias siguientes de pérdida de tiempo para conseguir retirar la parte rota a mitad del tubo del alimentador (ya sea en el tubo superior -del motor al HotEnd-, o en el inferior -de la bobina al motor-).

Le he estado dando vueltas, y creo que una forma de reducir bastante las probabilidades de que esto siga sucediendo con tanta regularidad (en mi caso 1 de cada 6-7 cargas/retiradas), sería cambiar las instrucciones que realiza durante el proceso...
Considero que la posición que tiene el tubo durante el proceso de carga/retirada es demasiado forzada, puesto que la máquina coloca los HotEnds en el fondo del eje Y, provocando que el tubo tome una curvatura bastante extrema.
Por lo tanto, quizás sólo con cambiar las instrucciones del Firmware para que, durante los procesos de carga y retirada de filamento, coloque los HotEnds en el extremo opuesto (en el frente y no en el fondo como ahora), las probabilidades de que esto suceda se reduzcan notablemente al dejar el tubo en una curvatura mucho más "agradecida".

Llevo un par de días probando esto mismo, puesto que los Steppers no se quedan bloqueados y antes de iniciar el proceso (una vez acabado el posicionamiento), puedo mover manualmente el carril de los HotEnds hasta la parte frontal. Lo estoy haciendo así desde las últimas 9 cargas/retiradas y por el momento no se me ha vuelto a partir el filamento.

Atentamente,
Eduard Miñana,
< 4 True Models >

PD: si estoy siendo demasiado pesado con tanta historia decídmelo, no quisiera hacer perder el tiempo a nadie, ni tampoco el mío propio.

**Comment by kitusmark** [comment]
Hola de nuevo @4truemodels.

El problema principal nace del propio material. En principio, Colorfila ya está trabajando en ello para conseguir que no se rompa.

Si que es verdad que la posición que adoptan los hotends en el momento de introducir el material no es la más cómoda ni para el filamento ni para el usuario que necesita ver el plástico salir.

Registramos el comentario y en próximas actualizaciones de firmware tomaremos una decisión.

Muchas gracias por todo este feedback. A nosotros nos va genial que personas como tú prueben la máquina de manera tan rigurosa.
