### ISSUE TITLE
[Question] Thermal Runaway Protection 

### ISSUE THREAD

**Issue by Zorgonaute84** [BCN3D/BCN3DSigma-Firmware#50]
Why did you don't active the thermal runaway protection in the Sigma Firmware ?

It looks as a good protection feature.

**Comment by kitusmark** [comment]
Hi @Zorgonaute84 ! It's true, I don't know why. We're going to work on that. Have you activated it? If so, what values have you set? in release 01-1.2.0 will be included.

Thanks!

**Comment by Zorgonaute84** [comment]
Heyyy it's sounds that BCN3D is in the good way to take care (more and more) about their users feedbacks ;-)

No I havn't activated it, I let the professionnals to do it.
