### ISSUE TITLE
[Issue]Extruder temperatures locked

### ISSUE THREAD

**Issue by sylus28** [BCN3D/BCN3DSigma-Firmware#57]
with last firmware T0 is off and temperature stay @209°C and T1 is off stay @77°C
No issue for bed.
Checked,no heating but big deviation of temp probes
Thanks for assistance

**Comment by kitusmark** [comment]
Hi @sylus28 

Have you managed to print something?
Please contact [technical support](mailto:sat@bcn3dtechnologies.com) and let me know when the problem is solved.

Thanks.

**Comment by sylus28** [comment]
Yes on extruder 1 if the print temp is over 210,
Issue happens after few print folowing the firmware upgrade
Thermistor and connections checked .
I have identify bad ADC value on both extruder (93 and 770 respectivly)
I have contact my local reseller (france) we are on it I 'll let you inform.

**Comment by kitusmark** [comment]
Ok. If it's firmware related it will be really really strange. We haven't change anything related with the temperature reading code. 

Sometimes it's a bad connection between the board in the carriage and the mainboard through the flat flexible cable. Remember if you mess with cables to turn off the printer first!

**Comment by sylus28** [comment]
flat cables and probes was removed and reinsert printer off

**Comment by sylus28** [comment]
EEPROM reset done according to reseler advice :no change issue still present

**Comment by kitusmark** [comment]
Hi @sylus28. I've been talking to tech support. This issue happened when updating the firmware or it happened before? Just for trying, have you tried to load v1.0.0 again?

**Comment by sylus28** [comment]
the issue appears few time after firmware update ( not suddenly)
trying to revert to each released firmware without success

**Comment by sylus28** [comment]
machine return for repair,not so happy....
