### ISSUE TITLE
Feature Request: Parallel print of same GCode on both extruder. 2x pieces with one print.

### ISSUE THREAD

**Issue by mrcg** [BCN3D/BCN3DSigma-Firmware#59]
It would be really excellent feature to print same 3d model on both extruder in parallel.
In theory it should be possible but not sure if Sigma FW does support this.

The printing volume needs to be halved from 210x297mm to 105x297.
The benefit of this "duplication" feature is to print 2 pieces in one print.
This will save lot of time and will be unique feature on the market !!!!

**Comment by pgilfernandez** [comment]
Hahaha, you have probably read my mind! since last week I had the same idea watching STACKER 3D printer on action, check this video:
[![stacker](https://i.ytimg.com/vi/otj6lsT8jYM/hqdefault.jpg)](https://www.youtube.com/watch?v=otj6lsT8jYM)

It would be great if our printer can have this cool feature =)

**Comment by 4truemodels** [comment]
+1... or better... +1million!

**Comment by sylus28** [comment]
+1

**Comment by flandaluce** [comment]
+1

**Comment by kapetanikolas** [comment]
that will be a kickass feature!  it will make the machine very competitive

**Comment by Zorgonaute84** [comment]
I don't think it's possible with the Sigma electronics. The Sigma is based on Arduibo, and Arduino is a single thread board. So it's not possible to provide the data for the boths extruders at the same time...

**Comment by kapetanikolas** [comment]
So the 8 bit atmega is not man enough to drive at the same time 6 motor?  
Not even by fooling the controller? say by sending the same signals to both extruders-X motors and hot ends?

**Comment by mrcg** [comment]
As a first step both extruders must move to it's initial position (Extruder_Left_X=50mm / Extruder_Right_X=150mm). Then the "feature" need to mirror all the X-axis stepper signals to both extruder (incl. filament extruder). Not sure if output can be mirrored in sync from the Sigma board.

If this in not possible then it would be possible (for sure) to do this "mechanically" by switch or relais.

The bigger challange i see in the correction of Noozle distance for both extruders in case they are differing more than 0,1mm.

**Comment by kapetanikolas** [comment]
Ive been getting my self familiar with the firmware latelly and got to the parts of the dual X axis
there are motion modes that one can set I guess Mode 2 would do what we are discussing. For the Z offset of the nozzles I wonder if the higher nozzle could be told to make a raft first to compensate? 

![firm](https://cloud.githubusercontent.com/assets/7797828/14906642/a02e7b1a-0db5-11e6-8798-16e1c26fc336.JPG)
