### ISSUE TITLE
Proceso de Calibración

### ISSUE THREAD

**Issue by 4truemodels** [BCN3D/BCN3DSigma-Firmware#6]
Hola de nuevo,

Ésta vez vengo a incordiaros por la rutina que sigue la máquina durante la "Full Calibration".
Quería comentar que me parece interesante intentar variar un poco las posiciones de ambos HotEnds en varios puntos del proceso para evitar que se queden fijos en al menos dos posiciones que considero posiblemente conflictivas: la primera es que el Nozzle se quede totalmente en contacto con la goma por la que debe pasar para limpiarse; la segunda es que se quede justo encima del borde de la plataforma que recoge el plástico sobrante durante las limpiezas, en este caso observo que sólo sucede con el Extrusor Derecho, y me parece la posición más crítica de todas, porque es muy posible que termine quemando un poco dicha plataforma (de hecho la mía ya tiene una pequeña marca).
En fin, que pensando en evitar futuros problemas arruinando la goma o parte de la plataforma de limpieza, he decidido compartir ésto con vosotros.

También echo de menos en la opción de "Bed Calibration" que una vez superado el proceso indicado (donde si es necesario la máquina te marca cómo mover los tornillos para alinearla, algo que me encanta), echo de menos que no repita el proceso donde pide alinear cada HotEnd de manera que quede en contacto con un folio, algo que sí realiza con el "Full Calibration", pero no con la opción de calibrar sólo la "Cama". 
Creo que estaría bien añadir ese punto y así evitar tener que completar el "Full..." cada vez que pretendo alinear la cama hasta ese nivel.

Venga, un saludo.
¡Muchas gracias por vuestro trabajo! ¡Esta SIGMA tiene muy buena pinta!

PD: ¿sería posible adquirir los modelos de las partes impresas de la máquina? ¡Necesito un recambio para uno de los soportes de las bobinas y otro para una de las sujeciones del cableado+tubo de la parte superior izquierda!

**Comment by neildarlow** [comment]
The cable and tube clip STL has already been placed onto youmagine.com following my request. They can break very easily during installation.
