### ISSUE TITLE
Preheating menu no longer works

### ISSUE THREAD

**Issue by Whoopsss** [BCN3D/BCN3DSigma-Firmware#63]
Hi, another strange issue.
This work early, then I got it was not working for custom materials but always for ABS and PLA, and now it does not work at all.
When I preheat, nothing happens.
I had this problem in V113, but the V114 upgrade changed nothing.

No problem for print.

Thanks.

**Comment by mrcg** [comment]
You only have the issue (pre heating not working) when you select custom filament temperatures. When you use PLA or ABS you have no issue. Is my understanding correct???


I also use custom filament temperatures and have another very strange behaviour. Issue could be related to the custom temp setting commands used from the SD towards EEPROM.
But this only a suspect for the moment.

**Comment by Whoopsss** [comment]
Hi,

After a new update of SD files and and .hex file, the preheat menu work like a charm ;-)

Thanks.
