### ISSUE TITLE
[Enhancement] Adjust the flow rates during printing in the settings menu.

### ISSUE THREAD

**Issue by Whoopsss** [BCN3D/BCN3DSigma-Firmware#64]
Hi,
An improvement would be to adjust the flow rate during printing in the settings menu.
Thanks.

**Comment by flandaluce** [comment]
+1

**Comment by cyranoidy** [comment]
+1

**Comment by nbald** [comment]
can I pay somebody for that feature ?

**Comment by guillemavila** [comment]
You already paid for the Sigma!

We're working on it. Mathematically easy, but needs new display files.

**Comment by shaneo1977** [comment]
+1

**Comment by atlemo** [comment]
+1
