### ISSUE TITLE
M504/M555 typo in Marlin_main.cpp (v114)

### ISSUE THREAD

**Issue by mrcg** [BCN3D/BCN3DSigma-Firmware#66]
Minor issue found in "Marlin_main.cpp":

_					case **504**: //**M555** Revert to default settings calibration and PID
					{
						Config_Reset_Calib();_

It should be M504 or M555 ... I guess it should be M504
Only minor commenting issue but should be corrected to reduce risk of confusion.

**Comment by kitusmark** [comment]
Fixed in the development branch
