### ISSUE TITLE
[Enhancement] adding recover print option

### ISSUE THREAD

**Issue by sylus28** [BCN3D/BCN3DSigma-Firmware#68]
As Marlin Thinkergnome firmware https://github.com/TinkerGnome/Ultimaker2Marlin/releases ,it will be nice to implement recover print fonction with scan code file and restart the printing @ failed Z height

**Comment by flandaluce** [comment]
+1

**Comment by kapetanikolas** [comment]
+1

**Comment by Wim1975** [comment]
+1
True, but then it would also be nice (necessary) if the Z height is shown during a print... so one knows where to restart it.

**Comment by sylus28** [comment]
+1
And also an filament detector based on that https://www.youtube.com/watch?v=7Bhbh1mcsi8
(currently repetier)

**Comment by AlejandroGarcia92** [comment]
We implement it for the upcoming new firmware version v01-1.2.2. 

Now avaliable in the Release Candidate. https://github.com/BCN3D/BCN3DSigma-Firmware/tree/v01-1.2.2RC
