### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by Kulitorum** [BCN3D/BCN3DSigma-Firmware#81]
What is the proper version of Arduino to compile this?

I just compiled the current source with Arduino 1.6.9. I got the following warnings:

In file included from sketch\ConfigurationStore.cpp:3:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

In file included from sketch\Hysteresis.cpp:26:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

sketch\Hysteresis.cpp: In member function 'void Hysteresis::InsertCorrection(const float&, const float&, const float&, const float&)':

sketch\Hysteresis.cpp:147:33: warning: narrowing conversion of '(((float)x) * axis_steps_per_unit[0])' from 'float' to 'long int' inside { } [-Wnarrowing]

  long destination[NUM_AXIS] = {x*axis_steps_per_unit[X_AXIS],y*axis_steps_per_unit[Y_AXIS],z*axis_steps_per_unit[Z_AXIS],e*axis_steps_per_unit[E_AXIS]}; 

                                 ^

sketch\Hysteresis.cpp:147:63: warning: narrowing conversion of '(((float)y) * axis_steps_per_unit[1])' from 'float' to 'long int' inside { } [-Wnarrowing]

  long destination[NUM_AXIS] = {x*axis_steps_per_unit[X_AXIS],y*axis_steps_per_unit[Y_AXIS],z*axis_steps_per_unit[Z_AXIS],e*axis_steps_per_unit[E_AXIS]}; 

                                                               ^

sketch\Hysteresis.cpp:147:93: warning: narrowing conversion of '(((float)z) * axis_steps_per_unit[2])' from 'float' to 'long int' inside { } [-Wnarrowing]

  long destination[NUM_AXIS] = {x*axis_steps_per_unit[X_AXIS],y*axis_steps_per_unit[Y_AXIS],z*axis_steps_per_unit[Z_AXIS],e*axis_steps_per_unit[E_AXIS]}; 

                                                                                             ^

sketch\Hysteresis.cpp:147:123: warning: narrowing conversion of '(((float)e) * axis_steps_per_unit[3])' from 'float' to 'long int' inside { } [-Wnarrowing]

  long destination[NUM_AXIS] = {x*axis_steps_per_unit[X_AXIS],y*axis_steps_per_unit[Y_AXIS],z*axis_steps_per_unit[Z_AXIS],e*axis_steps_per_unit[E_AXIS]}; 

                                                                                                                           ^

In file included from sketch\Marlin_main.cpp:41:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

sketch\Marlin_main.cpp:5072:33: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]

      LCD_MESSAGEPGM(MACHINE_NAME" "MSG_OFF".");

                                 ^

In file included from sketch\Marlin_main.cpp:54:0:

sketch\LCD_Handler.h: In function 'void myGenieEventHandler()':

sketch\LCD_Handler.h:1301:39: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"BED");

                                       ^

sketch\LCD_Handler.h:1311:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\LCD_Handler.h:1313:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\LCD_Handler.h:1318:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                   ^

sketch\LCD_Handler.h:1323:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                   ^

sketch\LCD_Handler.h:1351:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the left nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:1358:125: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the right nozzle \n and press GO, \n then the Z calibration will start");

                                                                                                                             ^

sketch\LCD_Handler.h:1362:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");      

                                                  ^

sketch\LCD_Handler.h:1372:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\LCD_Handler.h:1667:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                  ^

sketch\LCD_Handler.h:1684:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                 ^

sketch\LCD_Handler.h:1700:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                   ^

sketch\LCD_Handler.h:1719:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                 ^

sketch\LCD_Handler.h:1734:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                   ^

sketch\LCD_Handler.h:1751:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                   ^

sketch\LCD_Handler.h:1768:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                  ^

sketch\LCD_Handler.h:1785:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                 ^

sketch\LCD_Handler.h:1808:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                 ^

sketch\LCD_Handler.h:1825:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"Y AXIS, Heating");

                                                   ^

sketch\LCD_Handler.h:2167:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2169:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2180:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2185:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2211:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the right nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:2215:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2217:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2227:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2232:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2258:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the right nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:2263:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2265:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2279:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2284:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2310:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the right nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:2314:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2316:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2330:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2335:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2361:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the right nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:2365:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2367:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                 ^

sketch\LCD_Handler.h:2381:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2386:114: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                  ^

sketch\LCD_Handler.h:2412:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the right nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:2444:54: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"X AXIS, Heating...");

                                                      ^

sketch\LCD_Handler.h:2451:54: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"Y AXIS, Heating...");

                                                      ^

sketch\LCD_Handler.h:2530:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"X AXIS, Heating...");

                                                     ^

sketch\LCD_Handler.h:2540:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"X AXIS, Heating...");

                                                     ^

sketch\LCD_Handler.h:2551:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"X AXIS, Heating...");

                                                     ^

sketch\LCD_Handler.h:2562:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"X AXIS, Heating...");

                                                     ^

sketch\LCD_Handler.h:2573:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_AXIS,"X AXIS, Heating...");

                                                     ^

sketch\LCD_Handler.h:2697:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\LCD_Handler.h:2699:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\LCD_Handler.h:2704:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                   ^

sketch\LCD_Handler.h:2709:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                   ^

sketch\LCD_Handler.h:2736:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the left nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

sketch\LCD_Handler.h:2830:73: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_NAME_FILE,"                  Insert SD Card");//Printing form

                                                                         ^

sketch\Marlin_main.cpp: In function 'void setup()':

sketch\Marlin_main.cpp:722:49: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     genie.WriteStr(STRING_VERSION,VERSION_STRING);

                                                 ^

sketch\Marlin_main.cpp: In function 'void update_screen_noprinting()':

sketch\Marlin_main.cpp:1222:106: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_FILAMENT,"Press GO and keep pushing the filament \n until starts being pulled");

                                                                                                          ^

sketch\Marlin_main.cpp:1224:106: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_FILAMENT,"Press GO and keep pushing the filament \n until starts being pulled");

                                                                                                          ^

sketch\Marlin_main.cpp:1229:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_FILAMENT,"Press GO to Remove Filament, roll\n the spool backwards to save the filament");

                                                                                                                   ^

sketch\Marlin_main.cpp:1231:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_FILAMENT,"Press GO to Remove Filament, roll\n the spool backwards to save the filament");

                                                                                                                   ^

sketch\Marlin_main.cpp:1237:65: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

      genie.WriteStr(STRING_FILAMENT,"Press GO to Purge Filament");

                                                                 ^

sketch\Marlin_main.cpp: In function 'void process_commands()':

sketch\Marlin_main.cpp:3728:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\Marlin_main.cpp:3730:50: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_AXIS,"        Z AXIS");

                                                  ^

sketch\Marlin_main.cpp:3735:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                   ^

sketch\Marlin_main.cpp:3740:115: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Wait until the image \n turns red, the \n EXTRUDER are heating up");

                                                                                                                   ^

sketch\Marlin_main.cpp:3768:122: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       genie.WriteStr(STRING_CLEAN_INSTRUCTIONS,"Clean the left nozzle \n and press GO to move on to \n the next EXTRUDER");

                                                                                                                          ^

In file included from sketch\cardreader.cpp:5:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

In file included from sketch\planner.cpp:57:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

In file included from sketch\stepper.cpp:27:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

In file included from sketch\temperature.cpp:34:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

sketch\temperature.cpp:604:43: warning: extra tokens at end of #ifdef directive [enabled by default]

  #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                           ^

sketch\temperature.cpp:718:46: warning: extra tokens at end of #ifdef directive [enabled by default]

     #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                              ^

sketch\temperature.cpp:904:29: warning: extra tokens at end of #ifdef directive [enabled by default]

     #ifdef FILAMENT_SENSOR  && (FILWIDTH_PIN > -1)    //check if a sensor is supported 

                             ^

sketch\temperature.cpp:1170:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

In file included from sketch\ultralcd.cpp:1:0:

sketch\temperature.h:165:42: warning: extra tokens at end of #ifdef directive [enabled by default]

 #ifdef THERMAL_RUNAWAY_PROTECTION_PERIOD && THERMAL_RUNAWAY_PROTECTION_PERIOD > 0

                                          ^

Sketch uses 164,704 bytes (64%) of program storage space. Maximum is 253,952 bytes.
Global variables use 6,790 bytes (82%) of dynamic memory, leaving 1,402 bytes for local variables. Maximum is 8,192 bytes.
Low memory available, stability problems may occur.

**Comment by kitusmark** [comment]
For the most part you need the genie Library (LCD Screen) to compile.
You can find it here: https://github.com/4dsystems/ViSi-Genie-Arduino-Library

Try to download it and compile.
