### ISSUE TITLE
1.2.0 RC octoprint

### ISSUE THREAD

**Issue by sylus28** [BCN3D/BCN3DSigma-Firmware#82]
New features rocks.

Bad temperature for T1 to Octoprint 220°C on Sigma 155 for Octoprint
Recv: T:35.4 E:0 W:?
Recv: T:35.5 E:0 W:?
Recv: T:35.3 E:0 W:?

recover print and firmware will be awesome

edit
succes to initiate print with octoprint,but print lag

**Comment by sylus28** [comment]
Fan not start again after change filament

**Comment by AlejandroGarcia92** [comment]
We will investigate it.
Thank you for the feedback.
