### ISSUE TITLE
Bug: Dual print not aligned when printing from USB.

### ISSUE THREAD

**Issue by mrcg** [BCN3D/BCN3DSigma-Firmware#84]
When printing gcode with dual extrusion via USB (e.g. Octoprint) then T0 and T1 are not aligned according M530 calibration settings. When printing the same gcode via SD everything fully aligned according to calibration settings.

Issue verified with v1.1.6 and v1.2.0_RC.
![waste_tower_misalignment](https://cloud.githubusercontent.com/assets/4404991/16902142/509a9234-4c56-11e6-9c0b-dfaebed7964a.JPG)

**Comment by mrcg** [comment]
Issue still not fixed in v1.2.0 (from 23.09.2016).
This bug makes dual printing via USB impossible.

**Comment by AlejandroGarcia92** [comment]
Can you share with us this gcode file?

**Comment by mrcg** [comment]
Attached the gcode file. But this happens also with any other gcode file (dual extruder).
When printing via SD everything is ok and aligned. Printing same gcode via USB (octoprint) the extruders are not aligned.

https://dl.dropboxusercontent.com/u/20305979/github/calib_cube_3x3_layer.gcode

**Comment by AlejandroGarcia92** [comment]
We got the same issue but with more shift in Y axis than X, always by USB printing using this gcode. So we've tested some gcodes generated by Cura and we had no shift issues. Then we are going to still investigating what happens with it.

**Comment by mrcg** [comment]
I have sliced the same object also with Cura (everything default setting) and i have the same issue when printing via USB. Does not seem to be Simplify3D specific issue. When printing same gcode via SD everything is ok.

GCode generated with CURA (also not aligned when printing via USB):
![dual_not_aligned_when_printing_from_usb](https://dl.dropboxusercontent.com/u/20305979/github/dual_not_aligned_120_cura.JPG)

Cura GCode:
https://dl.dropboxusercontent.com/u/20305979/github/calib_cube_3x3_layer_cura.gcode

Could it be possible that FW does not take calibration data into consideration or using defaults from wrong motherboard (as defined in Configuration.h) when printing via USB?

My calibration data (M503):
Recv: echo: X 304.15 Y 0.05 Z -0.30 Z probe-1.70

**Comment by AlejandroGarcia92** [comment]
I have got those results:

![test-github](https://cloud.githubusercontent.com/assets/17469944/18909127/b066331c-8572-11e6-8a99-a3a3b0e96e61.jpg)

My calib data:

**Comment by mrcg** [comment]
Any finding/progress on this issue?

**Comment by mrcg** [comment]
What about correction for this issue?

**Comment by AlejandroGarcia92** [comment]
Doing some test in other printers, we got successful results without this kind issues. For us is difficult to fix this issue if we can not reproduce it. Anyway, we are aware of that issue.

**Comment by mrcg** [comment]
Beeing aware about this issue does not help me. I need a fix for this.
You already reproduced the issue and you should be able to analyze the root cause.
I need a solution/correction for this.

**Comment by AlejandroGarcia92** [comment]
I think that the problem is caused by mechanical origins but i hope that we can fix it via firmware. I will tell you my thoughs about it and also this will be added in the current RC firmware version ASAP.

**Comment by AlejandroGarcia92** [comment]
Firmware RC version updated. https://github.com/BCN3D/BCN3DSigma-Firmware/tree/v01-1.2.2RC

**Comment by mrcg** [comment]
Tested v1.2.2RC right now.
X-Axis seems to be solved now.
Unfortunately i have now shift in Y-Axis.
Can you fix this as well ???

![dual_not_aligned_1](https://cloud.githubusercontent.com/assets/4404991/20642448/4dd69c98-b40f-11e6-8ce0-7af9e86c20f0.jpg)

**Comment by mrcg** [comment]
I can not believe that it's so difficult to fix this issue.
This is really k.o. criteria to use commonly used printserver like octoprint.

**Comment by AlejandroGarcia92** [comment]
It seems that the problem happens because the printer doesn't block axis during change tool by USB and some vibrations shift it. Soon(Next Week), I'm going to update our RC version and I hope that it will work properly.

**Comment by AlejandroGarcia92** [comment]
@mrcg I have updated the version.

**Comment by mrcg** [comment]
@AlejandroGarcia92 Thanks for the "christmas present".

I will test it next week. Many thanks for your support.
I really hope it's fixing the issue. ;-)

**Comment by mrcg** [comment]
I have done some dual print via USB and the issue is fixed with latest 1.2.2RC.
**Great and many thanks for fixing this issue!!!**
The correction should be available in next official realease.

Issue to be closed now!!!

**Comment by guillemavila** [comment]
Awesome!
Thank you for the feedback, that's our goal bring you the most value from the Sigma :)
Yes it will be available in the next official update.

Have a nice printing Saturday!
