### ISSUE TITLE
[Enhancement] Menus where Printer is waiting for temperature reached, should show current temp

### ISSUE THREAD

**Issue by Isilrhofal** [BCN3D/BCN3DSigma-Firmware#88]
When I got my Sigma there has been a manufacturing problem where the band cable for the right extrude was not seated properly. This issue could have easily been identified ( 0C ) if the loading filament screen would show the temperature.

**Comment by AlejandroGarcia92** [comment]
In 1.2.0 version, you will see a percentage progress what is similar.
