### ISSUE TITLE
[Enhancement] Unloading filament should offer more control over the filament

### ISSUE THREAD

**Issue by Isilrhofal** [BCN3D/BCN3DSigma-Firmware#89]
When unloading some filament it happened to me several times that it got stuck in the bowens tube. (The original filament which came with the printer).
e.g.
Unload Filament

> Pause
> 
> > Move forward / backward
> > continue unload

In order to get this unstuck you currently need to:
1. Unload filament
2. Wait for the filament to be pulled back
3. power off if you find an issue
4. power on
5. pretend to load the filament / or use the purge option
6. cut the filament and finally unload.

**Comment by iDeveloUK** [comment]
FYI for speed i heat the hotends, purge about 10mm then manually pull the filament out. I then feed the new filament back in an purge a bit more. Its really quick and easy to do.
