### ISSUE TITLE
[Enhancement] Option to Reset Bed and Print Head location from UI

### ISSUE THREAD

**Issue by Isilrhofal** [BCN3D/BCN3DSigma-Firmware#90]
It would be handy if you could reset the Print Bed and Print Head location to default from the UI.

**Comment by guillemavila** [comment]
Hello, you can reset the bed location with the Move Z function. (Firmware v1.2.0+)
Head location can be moved by hand, and anytime the machine needs to find a specific head position it will home to get the zero.
