### ISSUE TITLE
Suggestion  

### ISSUE THREAD

**Issue by haqbany** [BCN3D/BCN3DSigma-Firmware#91]
I Have Suggestion  i noticed  that when the nozzle cools up sometimes some find huge filament drop stays in nozzle than it end up holding the nozzle stack in in the trash box  !! 

will be great if the nozzles will re do move the nozzles one more time after the temperature around 80c so it will clean the nozzle completely as the filament  is about the be hard and  easy broken  as machine default .

**Comment by AlejandroGarcia92** [comment]
In 1.2.0 version, the hotends still heated only after load/unload filament, purge or preheat. In addition, the hotends cool down after 10 min inactivity.
