### ISSUE TITLE
 2nd extruder the nozzle is not perfectly prime

### ISSUE THREAD

**Issue by haqbany** [BCN3D/BCN3DSigma-Firmware#92]
HI Please the 2nd extruder the nozzle is not perfectly prime ! Please help :-(

Thank you

**Comment by guillemavila** [comment]
What do you mean?

If you need to print with the right Hotend you can do that by just adding 'T1' as the first line before all the gcode generated by Cura. 

New profiles are coming where you can choose left/right Hotend while selecting the Cura profile, if you want to take a sneak peek that's gonna be pretty similar to the ones you can get here: https://github.com/BCN3D/BCN3DSigma-Profile-Generator
