### ISSUE TITLE
v01-1.2.0RCB XY shifting after pause

### ISSUE THREAD

**Issue by sylus28** [BCN3D/BCN3DSigma-Firmware#93]
During a print to avoid filament knot (extruder 2),activate pause then remove and reload filament ,after resuming X&Y axis shift.
remark travel of hotted was fast and hit endstop ( maybe speed should be decrease)

**Comment by AlejandroGarcia92** [comment]
It was a mistake/bug. In the 1.2.0, this issue is fixed.
